stages:

  data_ingestion:
    cmd: python src/Project_MultitaskModel/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Project_MultitaskModel/pipeline/stage_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/data